url: 'https://ideal-10.com'
baseurl: ''
lang: 'es-CO'
title: 'Ideal'

mailer: 'https://formspree.io/f/meoopabj'

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - package.json
  - package-lock.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
