- name: Soporte y mantenimiento a software desarrollados por la empresa.
  description: Garantizar el correcto funcionamiento del software desarrollado por la empresa, mediante la resolución de problemas, actualizaciones, mejoras, y asistencia técnica. También incluye monitoreo proactivo y adaptaciones para mantener compatibilidad y seguridad.
  svg: svg/code.svg

- name: Capacitación en el manejo de herramientas informáticas.
  description: Ofrecemos formación para asegurar el manejo eficiente de nuestras herramientas informáticas, facilitando su correcta aplicación y optimización en los procesos diarios.
  svg: svg/desktop-pc.svg

- name: Almacenamiento y conservación de información.
  description: Garantizamos el resguardo seguro y la preservación adecuada de la información, asegurando su disponibilidad e integridad a lo largo del tiempo.
  svg: svg/shield-check.svg

- name: Soporte contable y financiero a procesos administrativos públicos.
  description: Brindamos apoyo experto en contabilidad y finanzas para fortalecer la gestión eficiente de los procesos administrativos en entidades públicas.
  svg: svg/balance.svg

- name: Preparación y envío de información a los diferentes entes de control en entidades Públicas.
  description: Gestionamos la elaboración, validación y envío oportuno de información requerida por los diferentes entes de control, garantizando el cumplimiento normativo y la transparencia en las operaciones de las entidades públicas.
  svg: svg/cloud.svg

