- name: Soporte y mantenimiento a software desarrollados por la empresa.
  description: Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit, ab? Quidem vitae cupiditate dolor, ab minus eligendi. Incidunt nam atque odio temporibus, maxime, ullam illum facilis nihil tenetur repellat necessitatibus?
  svg: svg/cloud.svg

- name: Capacitación en el manejo de herramientas informáticas.
  description: Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit, ab? Quidem vitae cupiditate dolor, ab minus eligendi. Incidunt nam atque odio temporibus, maxime, ullam illum facilis nihil tenetur repellat necessitatibus?
  svg: svg/cloud.svg

- name: Almacenamiento y conservación de información.
  description: Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit, ab? Quidem vitae cupiditate dolor, ab minus eligendi. Incidunt nam atque odio temporibus, maxime, ullam illum facilis nihil tenetur repellat necessitatibus?
  svg: svg/cloud.svg

- name: Soporte contable y financiero a procesos administrativos públicos.
  description: Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit, ab? Quidem vitae cupiditate dolor, ab minus eligendi. Incidunt nam atque odio temporibus, maxime, ullam illum facilis nihil tenetur repellat necessitatibus?
  svg: svg/cloud.svg

- name: Preparación y envío de información a los diferentes entes de control en entidades Públicas.
  description: Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit, ab? Quidem vitae cupiditate dolor, ab minus eligendi. Incidunt nam atque odio temporibus, maxime, ullam illum facilis nihil tenetur repellat necessitatibus?
  svg: svg/cloud.svg

